version: "3.7"
services:
    web:
        image: ${DOCKER_REGISTRY:-agneisilva}/milesaway.web:${PLATFORM:-linux}-${TAG:-v1.0.0}
        container_name: milesaway_web
        restart: always
        build:
            context: .
            dockerfile: dockerfile
            args:
                - ANGULAR_ENVIRONMENT=production
        environment:
            - ConnectionStrings:Context=Server=milesaway_database;Database=Database;User Id=sa;Password=P4ssW0rd!;
        depends_on:
            - database
        networks:
            - network
        ports:
            - 8090:80
    database:
        image: microsoft/mssql-server-linux
        container_name: milesaway_database
        restart: always
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=P4ssW0rd!
        networks:
            - network
        ports:
            - 1433:1433
        volumes:
            - database:/var/opt/mssql
networks:
    network:
volumes:
    database:
